### ISSUE TITLE
Incomplete addresses in at least the first scraped applications shown in the morph UI

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/district_council_of_kimba_sa_development_applications#1]
For example "39 Schaefer Ave" rather than a complete address which includes a suburb and state.

See the help at https://www.planningalerts.org.au/how_to_write_a_scraper

> The physical address that this application relates to. This will be geocoded so doesn't need to be a specific format but obviously the more explicit it is the more likely it will be successfully geo-coded. If the original address did not include the state (e.g. "QLD") at the end, then add it.

**Comment by MichaelBone** [comment]
The raw data from the PDF files on the Kimba web site does not include a suburb name in most cases.  So I've updated the scraper to try to derive the suburb name from the street name (this is possible where a unique suburb name exists for a street name).  This means that streets which exist in multiple suburbs or unrecognized street names will still not have a suburb name; the development applications associated with any such addresses will now be ignored.
